# Exported from Render on 2026-08-23T21:17:40Z
version: "1"
services:
  - type: web
    name: ai-interface
    env: static
    buildCommand: bun install && bun run build
    staticPublishPath: .output/public
    branch: main
